name: latexmk
on:
  push:
    branches: master
    paths: 'paper/**'
  pull_request:
    branches: master
    paths: 'paper/**'
concurrency:
  group: latexmk-${{ github.ref }}
  cancel-in-progress: true
jobs:
  latexmk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: yegor256/latexmk-action@0.11.1
        with:
          path: paper
          opts: -pdf
          depends: paper/DEPENDS.txt
