# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: zerocracy
run-name: "zerocracy judges"
'on':
  schedule:
    - cron: '0,30 * * * *'
concurrency:
  group: zerocracy
  cancel-in-progress: false
jobs:
  zerocracy:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: zerocracy/judges-action@0.8.0
        with:
          verbose: false
          cycles: 1
          token: ${{ secrets.ZEROCRACY_TOKEN }}
          github_token: ${{ secrets.ZEROCRACY_GITHUB_PAT }}
          repositories: objectionary/*
          options: |
            vitals_url=https://www.eolang.org/zerocracy/objectionary-vitals.html
          factbase: objectionary.fb
      - uses: zerocracy/pages-action@0.1.0
        with:
          factbase: objectionary.fb
          output: pages
          logo: https://www.objectionary.com/cactus.svg
          options: |
            github_token=${{ secrets.ZEROCRACY_GITHUB_PAT }}
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: pages
          target-folder: zerocracy
          clean: false
